### PR TITLE
Enhancements

### PR DESCRIPTION
**Pull request by Nipun04**
This solves most of the issues:
1) Ios flickering
2) Last location
3) Go to location
4) Bookmarks
5) Highlights

Downside:
Code is based on Ionic V1 and need to be migrated to V3/4

### CODE REVIEW

**Comment by janpio** [comment]
Awesome!

As this is based on Ionic v1, if of course can't merge anything of it and having a PR doesn't make too much sense. Your repository being based on a fork of my repo, also isn't too useful as it is a fully different implementation.

My suggestion: Create a new `ionic-v1-epubjs` repository on Github and add your code there. I will then add a note to your Ionic v1 implementation to the README of my repository for people that are looknig for an implementation that does not have the problems of "mine".

**Comment by Nipun04** [comment]
Done 
https://github.com/Nipun04/Ionic-Reader

**Comment by janpio** [comment]
👍

**Comment by janpio** [comment]
Added here: https://github.com/janpio/ionic-epubjs/blob/master/README.md#related-projects

**Pull request closed without merging**
