### PR TITLE
Added useful files to read epub -zipped files

### PR DESCRIPTION
**Pull request by deIdris325**
ok

### CODE REVIEW

**Comment by deIdris325** [comment]
the files are from the epubjs lib. I added in the build folder. Now its
possible to "open" epub/3 files

2017-07-16 21:58 GMT+02:00 Jan Piotrowski <notifications@github.com>:

**Comment by janpio** [comment]
Does this really require all these files? Seems a bit much. I think we should really only add the stuff that is needed - this all has to be maintained :/

**Comment by deIdris325** [comment]
your r right!
I tested it with the following libs, and works! :
<script src="assets/epubjs/build/epub.min.js"></script>
<script src="assets/epubjs/build/libs/zip.min.js"></script>

**Comment by janpio** [comment]
Project already includes a `/libs/zip.min.js`. The current version also opens a .epub file without problems, so I think these changes are not needed.

Feel free to add the additional files again with future pull requests when you already implement functionality using them.

**Pull request closed without merging**
